# Generated by Django 6.0.4 on 2026-05-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ayudantias', '0001_initial'),
        ('cursos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudanteasignado',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudantias', to='users.alumno'),
        ),
        migrations.AddField(
            model_name='ayudanteasignado',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudantes', to='cursos.paralelo'),
        ),
        migrations.AddField(
            model_name='historialayudantias',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='users.alumno'),
        ),
        migrations.AddField(
            model_name='historialayudantias',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='cursos.paralelo'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='users.alumno'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='cursos.paralelo'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('alumno', 'paralelo')},
        ),
    ]
