"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lr0fv*kx3h2!5_^s-x4&*9aj8jcv%99k4snz&-(o^7ywr&0x7g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'social_django',
    'users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



###########################################################
#######ESTA PARTE ES DE LA BASE, LUEGO LA AJUSTAN!!########
###########################################################

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env(
    "SOCIAL_AUTH_GOOGLE_OAUTH2_KEY"
)

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env(
    "SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET"
)


LOGIN_REDIRECT_URL = "/users/success/"
LOGOUT_REDIRECT_URL = 'http://localhost:3000/'

###################################ESTE ES EL ORIGINAL, LUEGO QUITAR DE COMENTARIOS Y BORRAR LA V2.0
#SOCIAL_AUTH_PIPELINE = (
    #'social_core.pipeline.social_auth.social_details',
    #'social_core.pipeline.social_auth.social_uid',
    #'social_core.pipeline.social_auth.auth_allowed',
    #'social_core.pipeline.social_auth.social_user',
    #'social_core.pipeline.user.get_username',
    #'social_core.pipeline.user.create_user',

    # LOGICA DEL PIPELINE PARA ROLES!!!!!! esto es el anterior, lo pondremos comentario
    #para probar la version mockup, recordar borrar despues comentarios y la version mokup
    #'users.pipeline.save_user_role',

    #'social_core.pipeline.social_auth.associate_user',
    #'social_core.pipeline.social_auth.load_extra_data',
    #'social_core.pipeline.user.user_details',

###########################################aqui comienza la versión 2 con pipeline MOCKUP: 
SOCIAL_AUTH_PIPELINE = (

    'social_core.pipeline.social_auth.social_details',

    'social_core.pipeline.social_auth.social_uid',

    'social_core.pipeline.social_auth.auth_allowed',

    'social_core.pipeline.social_auth.social_user',

    'social_core.pipeline.user.get_username',

    'social_core.pipeline.user.create_user',

    'social_core.pipeline.social_auth.associate_user',

    'social_core.pipeline.social_auth.load_extra_data',

    'social_core.pipeline.user.user_details',

    'users.pipeline.redirect_user',
)
#)



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
