# Generated by Django 6.0.4 on 2026-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=20)),
                ('estado_final', models.CharField(choices=[('COMPLETADA', 'Completada'), ('INCOMPLETA', 'Incompleta'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Ayudantía',
                'verbose_name_plural': 'Historial de Ayudantías',
                'ordering': ['-semestre'],
            },
        ),
    ]
