# Generated by Django 6.0.4 on 2026-05-11 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistanthistory',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistanthistory',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='courses.section'),
        ),
    ]
