# Generated by Django 6.0.4 on 2026-05-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=20, unique=True)),
                ('nombre_curso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=10)),
                ('semestre', models.CharField(max_length=10)),
                ('estado_postulacion', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('vacantes', models.PositiveIntegerField(default=1)),
                ('ppa_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('requiere_entrevista', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='cursos.curso')),
            ],
        ),
    ]
