# Generated by Django 6.0.4 on 2026-05-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralelo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='users.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='paralelo',
            unique_together={('curso', 'seccion', 'semestre')},
        ),
    ]
