# Generated by Django 6.0.4 on 2026-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metodo_seleccion', models.CharField(choices=[('COORDINADOR', 'Un profesor coordina todos los paralelos'), ('INDIVIDUAL', 'Cada profesor elije su propio ayudante')], default='INDIVIDUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Secciones',
            },
        ),
    ]
