# Generated by Django 6.0.4 on 2026-05-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Seccion', 'verbose_name_plural': 'Secciones'},
        ),
    ]
