# Generated by Django 6.0.4 on 2026-07-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ayudantia_activa',
            field=models.BooleanField(default=True, help_text='Indica si el curso tiene ayudantía habilitada este semestre'),
        ),
    ]
