# Generated by Django 6.0.4 on 2026-06-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('oportunidad', models.IntegerField()),
                ('inscription_type', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_aprobadas', to='users.studentprofile')),
            ],
        ),
    ]
