# Generated by Django 6.0.4 on 2026-06-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='ppa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='sanciones',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='situacion_academica',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='departamento',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
