# Generated by Django 6.0.4 on 2026-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_approvedsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='alumno_activo',
            field=models.BooleanField(default=True),
        ),
    ]
