# Generated by Django 6.0.4 on 2026-07-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_alumno_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedsubject',
            name='inscription_type',
            field=models.CharField(max_length=50),
        ),
    ]
